auth/urls.py
from django.contrib import admin
from django.urls import path
from auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', views.Loginkar.as_view()),
    path('logout/', views.Logoutkar.as_view()),
]

main/urls.py
from django.contrib import admin
from django.urls import path
from main import views
from django.contrib.auth.decorators import login_required


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.Homehtml.as_view()),

    path('covidupdates/', views.Page2html.as_view()),

    path('guidelines/', views.Page3html.as_view()),

    path('registration/', views.Page4html.as_view()),
    
    path('beneficiary/', views.beneficiary),

    path('vaccine_center/', login_required(views.Vaccinecenter.as_view())),

    path('centers/', login_required(views.Centerlist.as_view())),

    path('centers/<int:pk>', login_required(views.Center.as_view()),name='centerdetail'),

    path('token/', views.token),
    ]

vaccinator/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('auth.urls'))
]

main/models.py
from django.db import models

# Create your models here.

STATE = {
    ('Maharashtra','Maharashtra')
}

CITY = {
    ('Pune','Pune'),
    ('Mumbai','Mumbai'),
    ('Nagpur','Nagpur'),
}

TIMESLOT = {
    ('10am to 1am','10am to 1am'),
    ('2pm to 6pm','2pm to 6pm')
}

class Vac_center(models.Model):


    name = models.CharField(max_length=256)
    state = models.CharField(max_length=256,choices=STATE)
    city = models.CharField(max_length=256,choices=CITY)
    centerid = models.IntegerField()
    vaccines_av = models.IntegerField()
    update = models.CharField(max_length=256)

    def __str__(self):
        return self.name

class Citizen(models.Model):

    name = models.CharField(max_length=256)
    mobno = models.CharField(max_length=256)
    age = models.IntegerField()
    state = models.CharField(max_length=256, choices=STATE )
    city = models.CharField(max_length=256, choices=CITY)
    center = models.CharField(max_length=256)
    centername = models.ForeignKey('Vac_center',on_delete=models.CASCADE)
    date = models.DateField()
    timeslot = models.CharField(max_length=256, choices=TIMESLOT)

    def __str__(self):
        return self.name

main/forms.py
from django import forms
from main import models

class Citizenform(forms.ModelForm):
    
    class Meta:
        model = models.Citizen
        fields = "__all__"
        
class Vac_centerform(forms.ModelForm):
    
    class Meta:
        model = models.Vac_center
        fields = "__all__"

main/views.py
from django.shortcuts import render,HttpResponse,HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.views import View
from django.views.generic import(
    TemplateView,
    DetailView,
    View,
    CreateView,
    FormView,
    ListView,
)
from django.contrib.auth.models import User
from main import forms
from main import models
from main.models import Citizen,Vac_center
from django.views.generic.detail import SingleObjectMixin,BaseDetailView



# Create your views here.

class Homehtml(View):
        def get(self,request):
            return render(request,'main/home.html')
            
class Page2html(View):
        def get(self,request):
            return render(request,'main/page2.html')
class Page3html(View):
        def get(self,request):
            return render(request,'main/page3.html')


class Page4html(View):
        def get(self,request):
            return render(request,'main/page4.html')
 
class Vaccinecenter(CreateView):
    model = models.Vac_center
    template_name = 'main/vaccine_center.html'
    fields = '__all__'
    success_url = '/centers'

class Center(DetailView):
    model = models.Vac_center
    context_object_name = 'centers'
    template_name = 'main/centerdetail.html'

class Centerlist(ListView):
    model = models.Vac_center
    context_object_name = 'centers'
    template_name = 'main/centers.html'

def beneficiary(request):

    vaccinecenters = models.Vac_center.objects.all()
    context={
        'vaccinecenters' : vaccinecenters
    }

    if request.method == "POST":
        name = request.POST.get('name')
        mobno = request.POST.get('mobno')
        age = request.POST.get('age')
        state = request.POST.get('state')
        city = request.POST.get('city')
        center = request.POST.get('center')    
        date = request.POST.get('date')    
        timeslot = request.POST.get('timeslot')    

        citizen_detail = Citizen(
        name =      name, 
        mobno =     mobno, 
        age =       age, 
        state =     state, 
        city =      city, 
        center =    center, 
        centername = center,
        date =      date, 
        timeslot =  timeslot 
        )

        citizen_detail.save()


    return render(request,"main/beneficiary.html",context)



def token(request):
    tokens = models.Citizen.objects.all()

    citizen = tokens
    citizen = citizen[::-1]
    context={
        'tokens' : citizen
    }
    return render(request,'main/token.html',context)


    

 















# class Vaccinecenter(CreateView,FormView):

#     model = models.Vac_center
#     form_class = forms.Vac_centerform
#     template_name = 'main/vaccine_center.html'

#     def form_valid(self,form):
#         obj = form.save()
#         obj.citizen = self.get_object()
#         obj.save()
#         return HttpResponseRedirect('/')

#     def post(self, request, *args, **kwargs):
#         self.object = self.get_object()
#         return super().post(request, *args, **kwargs)

#     def get(self, request, *args, **kwargs):
#         self.object = self.get_object()
#         context = self.get_context_data(object=self.object)
#         return self.render_to_response(context)
    


# class BaseDetailView(SingleObjectMixin, View):
#     """A base view for displaying a single object."""
#     def get(self, request, *args, **kwargs):
#         self.object = self.get_object()
#         context = self.get_context_data(object=self.object)
#         return self.render_to_response(context)
 

templates/main/beneficiary.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="icon" href="virus.png" type="image" sizes="16x16">

    <link rel="stylesheet" href=" {% static 'css/page5.css' %} ">

    <title>Register for Vaccination</title>
</head>

<body style="background-color: slateblue;">

    <!-- NAVBAR -->

    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Vaccinator</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="/">Home</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="/covidupdates/">Covid Updates</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="/guidelines/">Guidelines</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link active" href="/registration/">Registration</a>
                </li>

                </ul>

          </div>
        </div>
    </nav>
    <br><br><br><br><br>

    <h1>Get Your Token</h1>



    <div class="container">
        <form  method="POST" action="/token/" >
            {% csrf_token %}
            <div class="row">
                <div class="col-25">
                    <label for="fname">Full Name</label>
                </div>
                <div class="col-75">
                    <input required type="text" id="fname" name="name" placeholder="Your full name..">
                </div>
            </div>

            <div class="row">
                <div class="col-25">
                    <label for="mobileno">Mobile NO:</label>
                </div>
                <div class="col-75">
                    <input type="tel" id="mobileno" name="mobno" placeholder="Mobile number here" required >
                </div>
            </div>

            <div class="row">
                <div class="col-25">
                    <label for="ages">Age:</label>
                </div>
                <div class="col-75">
                    <input type="number" id="ages" name="age" placeholder="Your age" required >
                </div>
            </div>


            <div class="row">
                <div class="col-25">
                    <label for="State">State</label>
                </div>
                <div class="col-75">
                    <select id="State" name="state">
                        <option value="Maharashtra">Maharashtra</option>
                        <option value="Gujrat">Gujrat</option>
                    </select>
                </div>

            </div>
            <div class="row">
                <div class="col-25">
                    <label for="citys">city</label>
                </div>
                <div class="col-75">
                    <select id="citys" name="city">
                        <option value="Pune">pune</option>
                        <option value="Mumbai">Mumbai</option>
                        <option value="Nagpur">Nagpur</option>
                    </select>
                </div>

            </div>

            <div class="row">
                <div class="col-25">
                    <label for="Vaccination Center">Vaccination Center</label>
                </div>
                <div class="col-75">
                    <select id="Vaccination Center" name="center">
                        {% for centers in vaccinecenters %}
                        <option value="{{ centers.name }}">{{ centers.name }} </option>
                        {% endfor %}
                    </select>
                </div>
            </div>

            <div class="row">
                <div class="col-25">
                    <label for="dates">Select Date:</label>
                </div>
                <div class="col-75">
                    <input type="date" id="dates" name="date" placeholder="Schedule your vaccination" required >
                </div>
            </div>
            `

            <div class="row">
                <div class="col-25">
                    <label for="Choose Time Slot">Choose Time Slot</label>
                </div>
                <div class="col-75">
                    <div class="form-check">
                        <input class="form-check-input" value="10am to 1pm" type="radio" name="timeslot" id="flexRadioDefault">
                        <label class="form-check-label" for="flexRadioDefault">
                            10am to 1pm
                        </label>
                    </div>          
                    <div class="form-check">
                        <input class="form-check-input" value="2pm to 6pm" type="radio" name="timeslot" id="flexRadioDefault"
                            checked>
                        <label class="form-check-label" for="flexRadioDefault">
                            2pm to 6pm
                        </label>
                    </div>
                </div>
            </div>

            <div class="row">
                <input type="submit" value="Submit">
            </div>
        </form> 
    </div>



    <br><br>






    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"
        integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js"
        integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc"
        crossorigin="anonymous"></script>
</body>

</html>

templates/main/centerdetail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="icon" href="virus.png" type="image" sizes="16x16">
    <link rel="stylesheet" href="{% static 'css/page5.css' %}">


    <title>Vaccination Center Registration</title>
    <style>
        a{
            color: black;
        }
        a:hover{
            color: green;
        }
    </style>
</head>


<body style="background-color:rgb(53, 122, 190);">
    {% if user.is_authenticated %}

    <!-- NAVBAR -->

    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Vaccinator</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="/">Home</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="/covidupdates/">Covid Updates</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="/guidelines/">Guidelines</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link active" href="/registration/">Registration</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="/auth/logout/">LogOut</a>
                    </li>
                </ul>

          </div>
        </div>
    </nav>
    <br><br><br><br><br>



    <br><center><h2 style="color: white;">Citizens Details | click on name to view details <br>
        Name of Center: {{ centers.name }} 
      </h2></center><br><br>
    <table class="table table-striped table-success table-success table-hover"  >
        <thead>
          <tr>
            <th scope="col"> Sr.no </th>
            <th scope="col"> Name </th>
            <th scope="col"> Age </th>
            <th scope="col"> Centername </th>
            <th scope="col"> Date </th>
            <th scope="col"> Timeslot </th>
            <th scope="col"> Token No </th>

          </tr>
        </thead>
        <tbody>
            {% for citizen in centers.citizen_set.all %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td><strong><a href=""> {{ citizen.name}}</a></strong></td>
                <td><strong>{{citizen.age }}</strong></td>
                <td><strong>{{citizen.centername }}</strong></td>
                <td><strong>{{citizen.date }}</strong></td>
                <td><strong>{{citizen.timeslot }}</strong></td>
                <td><strong>{{citizen.pk }}</strong></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    </div>

        {% else %}
            <a href="auth/login/">Login Here</a>
            
        {% endif %}
    </div>



    <br><br>






    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"
        integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js"
        integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc"
        crossorigin="anonymous"></script>
</body>

</html>

templates/main/centers.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="icon" href="virus.png" type="image" sizes="16x16">
    <link rel="stylesheet" href="{% static 'css/page5.css' %}">


    <title>Vaccination Center Registration</title>
    <style>
        a{
            color: black;
        }
        a:hover{
            color: darkgreen;
        }
    </style>
</head>


<body style="background-color:rgb(53, 122, 190);">
    {% if user.is_authenticated %}

    <!-- NAVBAR -->

    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Vaccinator</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="/">Home</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="/covidupdates/">Covid Updates</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="/guidelines/">Guidelines</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link active" href="/registration/">Registration</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="/auth/logout/">LogOut</a>
                    </li>
                </ul>

          </div>
        </div>
    </nav>
    <br><br><br><br><br>



    <br><center><h2 style="color: white;">Center names | click on name to view details  </h2></center><br><br>
    <table class="table table-striped table-success table-success table-hover"  >
        <thead>
          <tr>
            <th scope="col"> Sr.no </th>
            <th scope="col"> Name </th>
            <th scope="col"> City </th>

          </tr>
        </thead>
        <tbody>
            {%  for center in centers %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td><strong><a href="{% url 'centerdetail' center.pk %}"> {{ center.name }}</a></strong></td>
                <td><strong>{{ center.city }}</strong></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

        {% else %}
            <a href="auth/login/">Login Here</a>
            
        {% endif %}
    </div>



    <br><br>






    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"
        integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js"
        integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc"
        crossorigin="anonymous"></script>
</body>

</html>

templates/main/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="icon" href="virus.png"  type="image" sizes="16x16">
    <title>Vaccinator</title>
</head>
<body>
/
    <!-- NAVBAR -->

    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Vaccinator</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/">Home</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="/covidupdates/">Covid Updates</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="/guidelines/">Guidelines</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="/registration/">Registration</a>
                </li>

                </ul>

          </div>
        </div>
    </nav><br><br><br>


    <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src="https://source.unsplash.com/900x350/?vaccine,medical" class="d-block w-100" alt="...">
          </div>
          <div class="carousel-item">
            <img src="https://source.unsplash.com/900x350/?injection" class="d-block w-100" alt="...">
          </div>
          <div class="carousel-item">
            <img src="https://source.unsplash.com/900x350/?medicine" class="d-block w-100" alt="...">
          </div>
          <div class="carousel-item">
            <img src="https://source.unsplash.com/900x350/?doctor" class="d-block w-100" alt="...">
          </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
    </div>



    
    <div class="p-5 mb-4 bg-light rounded-3">
        <div style="background-color: rgb(217, 233, 243);" class="container-fluid py-5">
          <h1 class="display-5 fw-bold">#IndiaFightsCorona COVID-19 </h1>
          <p class="col-md-8 fs-4">Our challenge is immense. Across the globe, the spread of COVID-19 continues to cause disease, death and disruption. It has pushed even the most advanced health systems to the brink. The crude mortality ratio for COVID-19 is estimated to be upwards of 3%, but can change from country to country, and even within countries. Key variables include access to care and the availability of testing.</p>
          <button class="btn btn-primary btn-lg" type="button">Support this fight</button>
        </div>
    </div>


    <div class="p-5 mb-4 bg-light rounded-3">
        <div style="background-color: rgb(217, 233, 243);" class="container-fluid py-5">
          <h1 class="display-5 fw-bold">WHO Guidelines for citizens</h1>
          <p class="col-md-8 fs-4">Our challenge is immense. Across the globe, the spread of COVID-19 continues to cause disease, death and disruption. It has pushed even the most advanced health systems to the brink. The crude mortality ratio for COVID-19 is estimated to be upwards of 3%, but can change from country to country, and even within countries. Key variables include access to care and the availability of testing.</p>
          <button class="btn btn-primary btn-lg" type="button">Support this fight</button>
        </div>
    </div><br><br>

<br><br>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
</body>
</html>

templates/main/page3.html

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="icon" href="virus.png"  type="image" sizes="16x16">
    <title>Guidelines</title>
</head>
<body>

    <!-- NAVBAR -->

    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Vaccinator</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="/">Home</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="/covidupdates/">Covid Updates</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link active" href="/guidelines/">Guidelines</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="/registration/">Registration</a>
                </li>

                </ul>

          </div>
        </div>
    </nav>
    

    <br><br><br><br>
    <center><h2>COVID-19 Guidelines</h2></center>
    
    <br><br>

    <div style="text-align: center; background-color: powderblue;">
        <iframe width="967" height="544" src="https://www.youtube.com/embed/Xj1nUFFVK1E" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </div><br><br>

    <div style="text-align: center; background-color:powderblue;">
        <iframe width="967" height="544" src="https://www.youtube.com/embed/jRV-ExaRSKQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe> 
    </div><br><br>

    <div style="text-align: center; background-color:powderblue;">
        <iframe width="967" height="544" src="https://www.youtube.com/embed/iADYeZ8JbB0?list=TLPQMTgwNDIwMjE8ElfOXEIO8w" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>  
    </div><br><br>

    <div style="text-align: center; background-color:powderblue;">
        <iframe width="967" height="544" src="https://www.youtube.com/embed/S3hm8CBWWew" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>    
    </div><br><br>

    <div style="text-align: center; background-color:powderblue;">
        <iframe width="967" height="544" src="https://www.youtube.com/embed/LS-mDwIlvoM?list=TLPQMTgwNDIwMjE8ElfOXEIO8w" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </div><br><br>


    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
</body>
</html>